name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libffi-dev libssl-dev python3-dev build-essential git zip unzip openjdk-8-jdk
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Install Android SDK tools
      run: |
        mkdir -p ~/.buildozer/android/platform
        curl -sL https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -o commandlinetools.zip
        unzip commandlinetools.zip -d ~/.buildozer/android/platform/android-sdk
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=~/.buildozer/android/platform/android-sdk "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    - name: Build APK
      run: |
        virtualenv venv
        source venv/bin/activate
        pip install buildozer
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: TaskApp-APK
        path: bin/*.apk
