name: Build APK
on: [push]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-22.04
    steps:
      - name: Set up environment variables
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      
      - name: Print GitHub Token
        run: echo "GitHub Token is $GITHUB_TOKEN"
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Buildozer dependencies
        run: |
          sudo apt update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-dev patch autoconf automake build-essential libtool pkg-config gettext zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libltdl-dev libssl-dev          
          pip install --upgrade buildozer
          echo 'export PATH=$PATH:~/.local/bin/' >> ~/.bashrc

      - name: Handle Java path
        run: |
         buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
