name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-11-jdk unzip git zip zlib1g-dev libncurses5-dev libffi-dev libssl-dev libreadline-dev libsqlite3-dev curl
        pip install --upgrade pip
        pip install buildozer cython

    - name: Download Android SDK Command-Line Tools
      run: |
        mkdir -p ~/.buildozer/android/platform/cmdline-tools/latest
        curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q sdk-tools.zip -d ~/.buildozer/android/platform/cmdline-tools/latest
        rm sdk-tools.zip

    - name: Set Android SDK environment variables
      run: |
        echo "ANDROID_HOME=$HOME/.buildozer/android/platform" >> $GITHUB_ENV
        echo "PATH=$HOME/.buildozer/android/platform/cmdline-tools/latest/bin:$HOME/.buildozer/android/platform/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Install Android SDK components
      run: |
        yes | ~/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager --licenses
        ~/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-31" "sources;android-31"

    - name: Build APK
      run: |
        buildozer android clean
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: Task-App-APK
        path: bin/*.apk
