name: Build APK
on: [push]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-22.04
    steps:
      - name: Set up environment variables
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      
      - name: Print GitHub Token
        run: echo "GitHub Token is $GITHUB_TOKEN"
        
      - name: Checkout
        uses: actions/checkout@v4
      - name: Accept Android SDK licenses 
        run: | 
         yes | sdkmanager --licenses

      - name: Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential
          sudo apt-get install libstdc++6
          sudo apt-get install aidl
          sudo apt-get install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev automake
          pip install --upgrade Cython virtualenv
          pip install --upgrade buildozer
          echo 'export PATH=$PATH:~/.local/bin/' >> ~/.bashrc


      - name: Handle Java path
        run: |
         buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
